// movies
export const GET_SEARCHED_MOVIES = 'GET_SEARCHED_MOVIES';
export const GET_SEARCHED_MOVIES_NAMES = 'GET_SEARCHED_MOVIES_NAMES';
export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const GET_SINGLE_MOVIE = 'GET_SINGLE_MOVIE';
// series
export const GET_SEARCHED_SERIES = 'GET_SEARCHED_SERIES';
export const GET_SEARCHED_SERIES_NAMES = 'GET_SEARCHED_SERIES_NAMES';
export const GET_POPULAR_SERIES = 'GET_POPULAR_SERIES';
export const GET_SINGLE_SERIES = 'GET_SINGLE_SERIES';
// genres
export const GET_MOVIE_GENRES = 'GET_MOVIE_GENRES';
export const GET_SERIES_GENRES = 'GET_SERIES_GENRES';