// movies
export const GET_SEARCHED_MOVIES = 'GET_SEARCHED_MOVIES';
export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const GET_SINGLE_MOVIE = 'GET_SINGLE_MOVIE';
// series
export const GET_SEARCHED_SERIES = 'GET_SEARCHED_SERIES';
export const GET_POPULAR_SERIES = 'GET_POPULAR_SERIES';
export const GET_SINGLE_SERIES = 'GET_SINGLE_SERIES';
